#!/usr/bin/env bash
#Program that prints FizzBuzz sequence
for j in {1..100}
do
    if [ $((j % 5)) -eq 0 -a $((j % 3)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((j % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((j % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$j"
    fi
done
